# Generated by Django 4.1.7 on 2023-05-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя, Фамилия'),
            preserve_default=False,
        ),
    ]
