# Generated by Django 4.1.7 on 2023-05-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.BooleanField(default=False, verbose_name='Доступ'),
        ),
    ]
