# Generated by Django 4.1.7 on 2023-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shashop', '0004_product_likes_alter_like_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='region',
            field=models.CharField(choices=[('ОШ', 'ОШ'), ('BISH', 'BISH'), ('ТАЛАС', 'ТАЛАС'), ('НАРЫН', 'НАРЫН'), ('ИК', 'ИК')], default=1, max_length=100),
        ),
    ]
